services:
  app:
    restart: unless-stopped
    build:
      context: .
      args:
        NEXT_PUBLIC_ADMIN_USERNAME: ${NEXT_PUBLIC_ADMIN_USERNAME:-admin}
        NEXT_PUBLIC_ADMIN_PASSWORD: ${NEXT_PUBLIC_ADMIN_PASSWORD:-password}
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
